services:
    db:
        image: postgres:15
        container_name: turbo-pg
        environment:
            POSTGRES_DATABASES: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
            - ./_db:/var/lib/postgresql/data
