services:
    db:
        image: postgres:16.6
        container_name: turbo-pg
        environment:
            - POSTGRES_DATABASES=${POSTGRES_DATABASES}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
            - ./_db:/var/lib/postgresql/dataß
