#!/bin/bash
set -e

POSTGRES_DB=${POSTGRES_DB:-"db"}
POSTGRES_USER=${POSTGRES_USER:-"user"}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-"password"}

echo "Creating database '$POSTGRES_DB' with credentials '$POSTGRES_USER' (user) '$POSTGRES_PASSWORD' (password)"

psql <<-EOSQL
    CREATE USER "$POSTGRES_USER" WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE "$POSTGRES_DB";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_DB";
EOSQL

